### ISSUE TITLE
Error: aggregate 'std::ostringstream oss' has incomplete type

### ISSUE THREAD

**Issue by LordCasser** [google/minimalloc#1]
When I compile this project, there is an error
![image](https://github.com/google/minimalloc/assets/35390821/f14fe090-f1c0-4387-be9e-a18115ec503a)

And I fixed it by add `#include <sstream>` in `minimalloc/src/converter.cc` 

![image](https://github.com/google/minimalloc/assets/35390821/7b5c672b-22b7-40df-aabb-1989f4c8221e)

I wanted to bring this to your attention so that it can be considered for improvement in future releases. Thank you for your attention to this matter.

**Comment by mmoffitt** [comment]
Thank you for the bug report!  I'll fix this right away.
