### ISSUE TITLE
paper required

### ISSUE THREAD

**Issue by VincentXWD** [google/minimalloc#5]
the paper link is unavailable anymore and i cannot find it even using google search. could you please provide a link of the paper or a pdf file?

**Comment by mmoffitt** [comment]
Yes, we're still waiting for ACM to upload the Volume 4 proceedings -- I've taken down that link until they manage to figure it out.

In the mean time, we can provide a preprint via email if that works for you (just contact moffitt@google.com and we'll reply with a PDF).

**Comment by mmoffitt** [comment]
The paper is [now online](https://dl.acm.org/doi/10.1145/3623278.3624752)!

**Comment by VincentXWD** [comment]
Great! Thanks a lot for letting me know!

Best Regards
Wendong Xu

**Comment by VincentXWD** [comment]
Great! Thanks a lot for letting me know!
