### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by cappadokes** [google/minimalloc#6]
Hi, awesome work! I'm trying to install `minimalloc` on Ubuntu 22.04.3 LTS, but I'm facing the problem described below. Looks like the external submodules used are not public.

Without the `--recursive` flag, build fails with `minimalloc/external/googletest does not contain a CMakeLists.txt file`.

*With* the `--recursive` flag, the repo cannot be cloned:

```bash
Cloning into 'minimalloc/external/googletest'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:google/googletest.git' into submodule path '/home/ideapilot/cmake-3.28.2/minimalloc/external/googletest' failed
Failed to clone 'external/googletest'. Retry scheduled
Cloning into 'minimalloc/external/googletest'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:google/googletest.git' into submodule path 'minimalloc/external/googletest' failed
Failed to clone 'external/googletest' a second time, aborting
```

Also note that `external/abseil-cpp` gets cloned just fine. Only `googletest` seems to be the problem.

Thx in advance!

**Comment by cappadokes** [comment]
Just tried; unfortunately I get the same error.

**Comment by mmoffitt** [comment]
OK, I just updated our `googletest` submodule to use HTTPS:

     https://github.com/google/minimalloc/commit/143a2c21ec52e8e5d07f0f6f8d92a635c4c15f4f

Can you try once more from scratch, using the same command above?

**Comment by cappadokes** [comment]
Problem solved. Thanks again!
